export const idiomas = [
  { codigo: 'es', nombre: 'Español' }, { codigo: 'ay', nombre: 'Aymara' },
  { codigo: 'en', nombre: 'English' }, { codigo: 'pt', nombre: 'Português' },
];

export const textos = {
  es: {
    'a11y.saltar': 'Saltar al contenido', 'nav.menu': 'Menú', 'nav.ubicacion': 'Dónde estamos', 'nav.arica': 'Qué visitar', 'nav.pedir': 'Cómo pedir',
    'nav.abrir': 'Abrir menú', 'nav.principal': 'Navegación principal', 'idioma.selector': 'Seleccionar idioma', 'whatsapp.cta': 'Pedir por WhatsApp',
    'hero.verMenu': 'Ver menú', 'menu.titulo': 'Nuestra carta', 'menu.categorias': 'Categorías de la carta', 'menu.pedir': 'Pedir',
    'menu.mensaje': 'Hola PizzArica, quiero pedir:', 'menu.extras': 'Extras', 'menu.tamanos': 'Tamaños', 'menu.sabores': 'Sabores de proteína: vainilla, chocolate, frutilla.',
    'menu.sabor': 'Sabor', 'menu.precioCarta': 'Según carta', 'arica.titulo': 'Qué visitar en Arica', 'arica.intro': 'Descubre algunos de los lugares y patrimonios que hacen única a nuestra ciudad.',
    'arica.seleccionar': 'Mostrar en el mapa', 'arica.llegar': 'Cómo llegar', 'arica.verMapa': 'Ver en Google Maps', 'arica.mapaTitulo': 'Mapa de', 'arica.atribucion': 'Datos de mapas © Google',
    'ubicacion.titulo': 'Dónde estamos', 'ubicacion.llegar': 'Cómo llegar', 'ubicacion.hoy': 'Hoy', 'ubicacion.cerrado': 'Cerrado', 'ubicacion.mapaTitulo': 'Mapa de ubicación de PizzArica', 'ubicacion.mapaPendiente': 'El mapa aparecerá cuando confirmemos la ubicación.',
    'pedido.titulo': 'Cómo pedir', 'galeria.titulo': 'Un pedacito de PizzArica', 'galeria.proxima': 'Próxima foto', 'galeria.todo': 'TODO: agregar foto real', 'footer.conversemos': 'Conversemos', 'footer.horario': 'Horario', 'footer.porConfirmar': 'Horario por confirmar',
  },
  // La interfaz general no se traduce al aymara: t() usa automáticamente el español como fallback. La carta y los lugares sí incluyen aymara en sus datos.
  ay: { 'nav.arica': 'Kunanakas uñjaña' },
  en: {
    'a11y.saltar':'Skip to content','nav.menu':'Menu','nav.ubicacion':'Find us','nav.arica':'What to see','nav.pedir':'How to order','nav.abrir':'Open menu','nav.principal':'Main navigation','idioma.selector':'Select language','whatsapp.cta':'Order on WhatsApp','hero.verMenu':'View menu','menu.titulo':'Our menu','menu.categorias':'Menu categories','menu.pedir':'Order','menu.mensaje':'Hello PizzArica, I would like to order:','menu.extras':'Extras','menu.tamanos':'Sizes','menu.sabores':'Protein flavors: vanilla, chocolate, strawberry.','menu.sabor':'Flavor','menu.precioCarta':'Menu price','arica.titulo':'What to see in Arica','arica.intro':'Discover some of the places and heritage that make our city unique.','arica.seleccionar':'Show on map','arica.llegar':'Get directions','arica.verMapa':'View on Google Maps','arica.mapaTitulo':'Map of','arica.atribucion':'Map data © Google','ubicacion.titulo':'Find us','ubicacion.llegar':'Get directions','ubicacion.hoy':'Today','ubicacion.cerrado':'Closed','ubicacion.mapaTitulo':'PizzArica location map','ubicacion.mapaPendiente':'The map will appear when we confirm the location.','pedido.titulo':'How to order','galeria.titulo':'A little piece of PizzArica','galeria.proxima':'Photo coming soon','galeria.todo':'TODO: add real photo','footer.conversemos':'Let’s talk','footer.horario':'Hours','footer.porConfirmar':'Hours to be confirmed',
  },
  pt: {
    'a11y.saltar':'Pular para o conteúdo','nav.menu':'Cardápio','nav.ubicacion':'Onde estamos','nav.arica':'O que visitar','nav.pedir':'Como pedir','nav.abrir':'Abrir menu','nav.principal':'Navegação principal','idioma.selector':'Selecionar idioma','whatsapp.cta':'Pedir pelo WhatsApp','hero.verMenu':'Ver cardápio','menu.titulo':'Nosso cardápio','menu.categorias':'Categorias do cardápio','menu.pedir':'Pedir','menu.mensaje':'Olá PizzArica, quero pedir:','menu.extras':'Extras','menu.tamanos':'Tamanhos','menu.sabores':'Sabores de proteína: baunilha, chocolate, morango.','menu.sabor':'Sabor','menu.precioCarta':'Conforme o cardápio','arica.titulo':'O que visitar em Arica','arica.intro':'Descubra alguns dos lugares e patrimônios que tornam nossa cidade única.','arica.seleccionar':'Mostrar no mapa','arica.llegar':'Como chegar','arica.verMapa':'Ver no Google Maps','arica.mapaTitulo':'Mapa de','arica.atribucion':'Dados do mapa © Google','ubicacion.titulo':'Onde estamos','ubicacion.llegar':'Como chegar','ubicacion.hoy':'Hoje','ubicacion.cerrado':'Fechado','ubicacion.mapaTitulo':'Mapa de localização da PizzArica','ubicacion.mapaPendiente':'O mapa aparecerá quando confirmarmos a localização.','pedido.titulo':'Como pedir','galeria.titulo':'Um pedacinho da PizzArica','galeria.proxima':'Próxima foto','galeria.todo':'TODO: adicionar foto real','footer.conversemos':'Fale conosco','footer.horario':'Horário','footer.porConfirmar':'Horário a confirmar',
  },
};
Object.assign(textos.es, {'hero.linea1':'Pizza al paso,','hero.linea2':'hecha en Arica','hero.apoyo':'Ingredientes frescos y sabor local, preparados al momento en nuestro food truck.','pedido.paso1':'Elige tu pizza en la carta.','pedido.paso2':'Escríbenos por WhatsApp.','pedido.paso3':'Retira en el truck.','estado.abierto':'Abierto hasta las','estado.cerradoHasta':'Cerrado, abrimos el','estado.aLas':'a las','estado.temporal':'Cerrado temporalmente'});
Object.assign(textos.en, {'hero.linea1':'Pizza on the go,','hero.linea2':'made in Arica','hero.apoyo':'Fresh ingredients and local flavor, prepared to order in our food truck.','pedido.paso1':'Choose your pizza from the menu.','pedido.paso2':'Message us on WhatsApp.','pedido.paso3':'Pick it up at the truck.','estado.abierto':'Open until','estado.cerradoHasta':'Closed, we open on','estado.aLas':'at','estado.temporal':'Temporarily closed'});
Object.assign(textos.pt, {'hero.linea1':'Pizza para levar,','hero.linea2':'feita em Arica','hero.apoyo':'Ingredientes frescos e sabor local, preparados na hora em nosso food truck.','pedido.paso1':'Escolha sua pizza no cardápio.','pedido.paso2':'Fale conosco pelo WhatsApp.','pedido.paso3':'Retire no truck.','estado.abierto':'Aberto até','estado.cerradoHasta':'Fechado, abrimos','estado.aLas':'às','estado.temporal':'Fechado temporariamente'});
