import { useEffect, useRef, useState } from 'react';
import { categorias, encabezadosJugos, extras, notaBatidos, prefijos, productos, tamanos } from '../data/carta';
import { usePedido } from '../context/PedidoContext';
import { useIdioma } from '../i18n/IdiomaContext';
import PedidoPanel from './PedidoPanel';
import '../styles/Menu.css';
const money = new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0});
const bases=['agua','soprole','gloria','sin-lactosa'];
export function nombreProducto(id,idioma){for(const categoria of categorias){const item=productos[categoria.id].find(x=>x.id===id);if(item){const nombre=typeof item.nombre==='string'?item.nombre:item.nombre[idioma]??item.nombre.es;return `${prefijos[categoria.id]?.[idioma]||''} ${nombre}`.trim()}}return id}
export function nombreVariante(variante,idioma,t){if(variante==='individual')return t('pedido.individual');if(variante==='familiar')return t('pedido.familiar');const i=bases.indexOf(variante);return i>=0?(encabezadosJugos[idioma]?.[i]??encabezadosJugos.es[i]):variante}
function Quantity({linea,nombre,onChange,t}){return <span className="quantity"><button onClick={()=>onChange(linea.key,linea.cantidad-1)} aria-label={`${t('pedido.disminuir')} ${nombre}`}>−</button><b>{linea.cantidad}</b><button onClick={()=>onChange(linea.key,linea.cantidad+1)} aria-label={`${t('pedido.aumentar')} ${nombre}`}>+</button></span>}
function ProductAction({item,categoria,nombre,onAnnounce}){const{idioma,t}=useIdioma();const{items,agregar,cambiarCantidad}=usePedido();const[abierto,setAbierto]=useState(false);const variantes=categoria==='pizzas'?[{id:'individual',precio:5990},{id:'familiar',precio:item.precio}]:categoria==='jugos'?item.precios.map((precio,i)=>precio&&({id:bases[i],precio})).filter(Boolean):[];const lineas=items.filter(x=>x.id===item.id);const add=variante=>{agregar({id:item.id,variante:variante?.id,precioUnitario:variante?.precio??item.precio});setAbierto(false);onAnnounce(`${t('pedido.agregado')} ${nombre}`)};const clickAdd=()=>variantes.length>1?setAbierto(v=>!v):add(variantes[0]);return <div className="product-action">{lineas.map(linea=><div className="product-action__selected" key={linea.key}><small>{linea.variante&&nombreVariante(linea.variante,idioma,t)}</small><Quantity linea={linea} nombre={nombre} onChange={cambiarCantidad} t={t}/></div>)}{(!lineas.length||variantes.length>1)&&<button className="add-button" onClick={clickAdd} aria-expanded={variantes.length>1?abierto:undefined} aria-label={`${t('pedido.agregar')} ${nombre}`}>{t('pedido.agregar')}</button>}{abierto&&<div className="variant-picker" aria-label={categoria==='pizzas'?t('pedido.tamano'):t('pedido.base')}>{variantes.map(v=><button key={v.id} onClick={()=>add(v)}><span>{nombreVariante(v.id,idioma,t)}</span><strong>{money.format(v.precio)}</strong></button>)}</div>}</div>}
export default function Menu(){const{idioma,t}=useIdioma();const{items}=usePedido();const[active,setActive]=useState(0),[changing,setChanging]=useState(false),[announcement,setAnnouncement]=useState('');const tabs=useRef([]),wrap=useRef();const[ind,setInd]=useState({x:0,w:0});const measure=()=>{const el=tabs.current[active],box=wrap.current;if(el&&box)setInd({x:el.offsetLeft-box.scrollLeft,w:el.offsetWidth})};useEffect(measure,[active,idioma]);useEffect(()=>{addEventListener('resize',measure);return()=>removeEventListener('resize',measure)});const choose=i=>{if(i===active)return;setChanging(true);setTimeout(()=>{setActive(i);setChanging(false)},120)};const keys=e=>{let i=active;if(e.key==='ArrowRight')i=(i+1)%categorias.length;else if(e.key==='ArrowLeft')i=(i-1+categorias.length)%categorias.length;else return;e.preventDefault();choose(i);tabs.current[i]?.focus()};const cat=categorias[active],list=productos[cat.id];return <section id="menu" className="section menu" aria-labelledby="menu-title"><div className="container"><h2 id="menu-title">{t('menu.titulo')}</h2><div className="menu-layout"><div><div className="tabs" role="tablist" aria-label={t('menu.categorias')} ref={wrap} onScroll={measure}>{categorias.map((c,i)=><button ref={el=>tabs.current[i]=el} role="tab" aria-selected={i===active} tabIndex={i===active?0:-1} id={`tab-${i}`} aria-controls="menu-panel" key={c.id} onClick={()=>choose(i)} onKeyDown={keys}>{c.nombre[idioma]}</button>)}<span className="tabs__indicator" style={{transform:`translateX(${ind.x}px) scaleX(${ind.w})`}}/></div><div id="menu-panel" role="tabpanel" aria-labelledby={`tab-${active}`} className={`menu-list ${changing?'is-changing':''}`}>{list.map(item=>{const nombre=nombreProducto(item.id,idioma),hasItem=items.some(x=>x.id===item.id);return <article className={`menu-item ${hasItem?'is-selected':''}`} key={item.id}><div className="menu-item__content"><div className="menu-item__line"><h3>{item.emoji&&<span aria-hidden="true">{item.emoji} </span>}{nombre}</h3><span/><strong>{cat.id==='jugos'?item.precios.filter(Boolean).map(x=>money.format(x)).join(' / '):money.format(item.precio)}</strong><ProductAction item={item} categoria={cat.id} nombre={nombre} onAnnounce={setAnnouncement}/></div>{item.ingredientes&&<p>{item.ingredientes[idioma]}</p>}</div></article>})}{cat.id==='batidos'&&<div className="menu-note"><strong>{t('menu.sabores')}</strong><p>{notaBatidos[idioma]}</p></div>}</div><div className="menu-addons"><div><h3>{t('menu.extras')}</h3>{extras.map(x=><p key={x.precio}><strong>+{money.format(x.precio)}</strong> — {x.texto[idioma]}</p>)}</div><div><h3>{t('menu.tamanos')}</h3>{tamanos.map(x=><p key={x.nombre}><strong>{x.nombre}{x.precio?` — ${money.format(x.precio)}`:''}</strong> — {x.texto[idioma]}</p>)}</div></div></div><aside className="order-sidebar"><PedidoPanel/></aside></div><p className="sr-only" aria-live="polite">{announcement}</p></div></section>}
